# Generated by Django 5.1.7 on 2025-03-12 11:02

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="time",
            field=models.TimeField(default=core.models.default_exam_time),
        ),
        migrations.AlterField(
            model_name="queue",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_entries",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
