# Generated by Django 5.1.7 on 2025-03-12 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_exam_time_alter_queue_tag_alter_tag_tag_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username must be in the format xx/yyyy (e.g., 21/2001).",
                        regex="^[0-9]{2}/[0-9]{4}$",
                    )
                ],
            ),
        ),
    ]
