# Generated by Django 5.1.7 on 2025-03-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_student_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="name",
            new_name="course_name",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="venue",
        ),
        migrations.AddField(
            model_name="exam",
            name="course_code",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
