# Generated by Django 5.1.7 on 2025-03-15 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_name_exam_course_name_remove_exam_venue_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queue",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="queue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queue",
            name="tag_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
