# Generated by Django 5.1.7 on 2025-03-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_queue_options_queue_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="date",
            new_name="exam_date",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="time",
            new_name="start_time",
        ),
    ]
