# Generated by Django 5.1.7 on 2025-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_date_exam_exam_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
