# Generated by Django 5.1.7 on 2025-03-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_exam_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="joined_at",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="tag",
        ),
        migrations.AddField(
            model_name="queue",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
