# Generated by Django 5.1.7 on 2025-03-18 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_queue_joined_at_remove_queue_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queue",
            old_name="completed_at",
            new_name="checked_out_at",
        ),
        migrations.AddField(
            model_name="queue",
            name="first_check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queue",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tag",
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="queue",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.exam"
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("checked_in", "Checked In"),
                    ("completed", "Completed"),
                    ("checked_out", "Checked Out"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="tag_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
